version: '3'

tasks:
  all:
    desc: Run all tests
    deps:
      - noisy_sum
      - prefix_sum
      - noisy_max
      - svt5
      - svt6
      - laplace_parallel
      - onetime_rappor
      - rappor
      - truncated_geometric
  noisy_sum:
    desc: algorithm NoisySum
    cmds:
      - echo "correct_eps=0.1"
      - python -m test.alg.noisy_sum
  prefix_sum:
    desc: algorithm PrefixSum
    cmds:
      - echo "correct_eps=0.1"
      - python -m test.alg.prefix_sum
  noisy_max_lap:
    desc: algorithm NoisyMaxLap
    cmds:
      - echo "correct_eps=0.5"
      - python -m test.alg.noisy_max_lap
  noisy_max_exp:
    desc: algorithm NoisyMaxExp
    cmds:
      - echo "correct_eps=0.5"
      - python -m test.alg.noisy_max_exp
  noisy_arg_max_lap:
    desc: algorithm NoisyArgMaxLap
    cmds:
      - echo "correct_eps=0.1"
      - python -m test.alg.noisy_arg_max_lap
  noisy_arg_max_exp:
    desc: algorithm NoisyArgMaxExp
    cmds:
      - echo "correct_eps=0.1"
      - python -m test.alg.noisy_arg_max_exp
  svt1:
    desc: algorithm SVT1
    cmds:
      - echo "correct_eps=0.1"
      - python -m test.alg.svt1
  svt2:
    desc: algorithm SVT2
    cmds:
      - echo "correct_eps=0.1"
      - python -m test.alg.svt2
  svt4:
    desc: algorithm SVT4
    cmds:
      - echo "correct_eps=0.18"
      - python -m test.alg.svt4
  svt5:
    desc: algorithm SVT5
    cmds:
      - echo "correct_eps=inf"
      - python -m test.alg.svt5
  svt6:
    desc: algorithm SVT6
    cmds:
      - echo "correct_eps=inf"
      - python -m test.alg.svt6
  laplace_parallel:
    desc: algorithm=LaplaceParallel, adj=1
    cmds:
      - echo "correct_eps=0.1"
      - python -m test.alg.laplace_parallel
  onetime_rappor:
    desc: algorithm=OneTimeRappor, adj=1
    cmds:
      - echo "correct_eps=0.8"
      - python -m test.alg.onetime_rappor
  rappor:
    desc: algorithm=Rappor, adj=1
    cmds:
      - echo "correct_eps=0.4"
      - python -m test.alg.rappor
  truncated_geometric:
    desc: algorithm=TruncatedGeometric, adj=1
    cmds:
      - echo "correct_eps=0.12"
      - python -m test.alg.truncated_geometric
